### ISSUE TITLE
Does not work with kibana 5.5.0 ? 

### ISSUE THREAD

**Issue by pasterio** [outbrain/ob-kb-funnel#8]

**Comment by yershalom** [comment]
Hi @pasterio
I don't have a running 5.5.0 running kibana yet. If I'll make a new release can you test it?

**Comment by pasterio** [comment]
do it and I will test right away

**Comment by yershalom** [comment]
You got it, https://github.com/outbrain/ob-kb-funnel/releases/tag/v5.5.0

**Comment by pasterio** [comment]
Attempting to transfer from https://github.com/outbrain/ob-kb-funnel/archive/v5.5.0.zip
Transferring 5651327 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by yershalom** [comment]
Hi,
Follow this thread. https://github.com/bitsensor/elastalert-kibana-plugin/issues/6

**Comment by pasterio** [comment]
ERROR in ./plugins/ob-kb-funnel/public/funnelController.js
    Module not found: Error: Cannot resolve module 'd3-funnel' in /usr/share/kibana/plugins/ob-kb-funnel/public
     @ ./plugins/ob-kb-funnel/public/funnelController.js 6:15-35

**Comment by yershalom** [comment]
You need to run npm install

**Comment by KAYLukas** [comment]
I ran npm install and now I get this error:
Error: Uncaught TypeError: __webpack_require__(...).register is not a function (http://localhost:5601/bundles/kibana.bundle.js?v=1:262)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=1:90:20880)

**Comment by bigtoerag** [comment]
Also having issue on 5.5.2 doing a local offline install after bumping package version number.

`@linux:/usr/share/kibana# bin/kibana-plugin install file:///usr/share/kibana/network_vis.zip
Attempting to transfer from file:///usr/share/kibana/network_vis.zip
Transferring 11698176 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /usr/share/kibana/node_modules/yauzl/index.js:179:14
    at /usr/share/kibana/node_modules/yauzl/index.js:539:5
    at /usr/share/kibana/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:682:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"
`
Other plugins have installed fine: swimlane, cohort
Is there a dependency missing or config issue?

**Comment by sairamvla** [comment]
Did not work on 5.5.0. It's throwing this error -

 log   [19:53:44.687] [fatal] Error: Optimizations failure.

    ERROR in ../plugins/ob-kb-funnel-5.5.0/~/xmlhttprequest/lib/XMLHttpRequest.js
    Module not found: Error: Cannot resolve module 'child_process' in /etc/kibana-5.5.0-linux-x86_64/plugins/ob-kb-funnel-5.5.0/node_modules/xmlhttprequest/lib
     @ ../plugins/ob-kb-funnel-5.5.0/~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36

**Comment by sairamvla** [comment]
Any update on 5.5.0 issues?

**Comment by seanziee** [comment]
I getting a
 ``` ERROR in ./plugins/kibana/~/xmlhttprequest/lib/XMLHttpRequest.js
    Module not found: Error: Cannot resolve module 'child_process' in /kibana-5.5.0-darwin-x86_64/plugins/kibana/node_modules/xmlhttprequest/lib
     @ ./plugins/kibana/~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36
```
When  installing in 5.5.0
